/****************************************************************************************************
Class Name      : RHM_Constants
Description     : This class is used for storing all the constants used in the entire codebase
Created By      : Deloitte
Created Date    : April 20, 2020
Modification Log:
-----------------------------------------------------------------------------------------------------
Developer                   Date                        Description
-----------------------------------------------------------------------------------------------------
Shivam                April 20, 2020                 Initial Version
*****************************************************************************************************/
public class RHM_Constants {    
    public static final String RECORD_HISTORY_API_NAME = 'RHM_Record_History__c';
    public static final String RECORD_TYPE_RECORD_HISTORY_INSERT = 'RHM_Insert';
    public static final String RECORD_TYPE_RECORD_HISTORY_UPDATE = 'RHM_Update';
    public static final String RECORD_TYPE_RECORD_HISTORY_DELETE = 'RHM_Delete';
    public static final String RECORD_TYPE_RECORD_HISTORY_UNDELETE = 'RHM_Undelete';
    public static final String RECORD_TYPE_TASK_DELETE_REQUEST = 'RHM_Delete_Request';
}